language: cpp
compiler: clang
matrix:
  include:
  # works on Trusty
  - os: linux
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo apt install libboost-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
