version: 2

jobs:
  build:
    docker:
      - image: "fedora:30"
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: 'sudo dnf install -y g++ cmake boost-devel tbb-devel git make'
      - run:
          name: Creating build files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating binaries
          command: 'cmake --build build'
      - run:
          name: Unit tests
          command: 'cd build && ctest --verbose'